Test.Env=Local
Base.URL=http://127.0.0.1/opencart
Test.Framework=Python + requests + pytest
Report.Type=Allure
Executor=Local
OS=Windows 10
Python.Version=3.11.5
Requests.Version=2.32.3
Pytest.Version=9.1.1
Browser=Chrome
Test.Date=2026-07-27